import type { Campaign } from './types';

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: '1',
    title: 'Digital Literacy for Seniors',
    creator: 'TechConnect Elders',
    creatorAvatar: 'https://picsum.photos/seed/creatorA/40/40',
    description: 'Help seniors connect with their loved ones and the digital world by funding tech workshops.',
    longDescription: 'In an increasingly digital age, many seniors are left feeling isolated. TechConnect Elders provides free, patient, and friendly workshops to teach essential skills like video calling, online safety, and accessing telehealth services. Your donation funds tablets, learning materials, and volunteer training, empowering the elderly to stay connected with family, friends, and vital services.',
    imageUrl: 'https://picsum.photos/seed/seniors/600/400',
    goalAmount: 8000,
    currentAmount: 3400,
    donors: 78,
    category: 'Community',
    endDate: '2024-12-20',
  },
  {
    id: '2',
    title: 'Mobile Health Clinic for Remote Areas',
    creator: 'Health on Wheels',
    creatorAvatar: 'https://picsum.photos/seed/creatorB/40/40',
    description: 'Bring essential medical check-ups and basic healthcare to isolated communities.',
    longDescription: 'For those living in remote regions, a simple doctor\'s visit can be an all-day journey. Our Mobile Health Clinic is a specially equipped van staffed by volunteer nurses and doctors that travels to these underserved areas. We provide vaccinations, health screenings, and basic medical care. Your support keeps our clinic on the road, stocked with supplies, and ready to serve.',
    imageUrl: 'https://picsum.photos/seed/health/600/400',
    goalAmount: 22000,
    currentAmount: 19500,
    donors: 250,
    category: 'Health',
    endDate: '2024-11-15',
  },
  {
    id: '3',
    title: 'Urban Beekeeping Initiative',
    creator: 'City Hive Project',
    creatorAvatar: 'https://picsum.photos/seed/creatorC/40/40',
    description: 'Support local ecosystems by establishing and maintaining beehives on city rooftops.',
    longDescription: 'Bees are vital to our ecosystem, and you can help them thrive even in the city! The City Hive Project installs and maintains beehives on the rooftops of partnering businesses and community buildings. These hives help pollinate urban gardens and parks, increasing biodiversity. Your donation helps us build new hives, purchase safety equipment, and run educational programs about the importance of pollinators.',
    imageUrl: 'https://picsum.photos/seed/bees/600/400',
    goalAmount: 12000,
    currentAmount: 6800,
    donors: 112,
    category: 'Environment',
    endDate: '2025-03-01',
  },
  {
    id: '4',
    title: 'Revitalize the Local Community Theater',
    creator: 'Spotlight Arts',
    creatorAvatar: 'https://picsum.photos/seed/creatorD/40/40',
    description: 'Help us renovate our beloved but aging theater with new seats, sound, and lighting.',
    longDescription: 'The Oakwood Community Theater has been a hub for local arts for over 50 years, but it\'s in desperate need of an upgrade. Our seats are worn, our sound system crackles, and our lighting is outdated. This campaign will fund essential renovations to create a safe, comfortable, and technically advanced space for our performers and audience. Help us keep the magic of live theater alive in our town for generations to come.',
    imageUrl: 'https://picsum.photos/seed/theater/600/400',
    goalAmount: 40000,
    currentAmount: 25600,
    donors: 198,
    category: 'Arts',
    endDate: '2025-02-01',
  },
  {
    id: '5',
    title: 'Therapy Dog Training Program',
    creator: 'Healing Paws',
    creatorAvatar: 'https://picsum.photos/seed/creatorE/40/40',
    description: 'Fund the training and certification of therapy dogs to comfort people in hospitals and schools.',
    longDescription: 'The unconditional love of a dog has incredible healing power. Healing Paws trains and certifies gentle-tempered dogs and their handlers to work as therapy teams. They visit hospitals, nursing homes, and schools to provide comfort, reduce stress, and bring joy. Your donation covers the cost of expert training, certification exams, and volunteer gear, allowing us to bring more wagging tails to those who need them most.',
    imageUrl: 'https://picsum.photos/seed/dogs/600/400',
    goalAmount: 15000,
    currentAmount: 14800,
    donors: 401,
    category: 'Animals',
    endDate: '2024-10-10',
  },
  {
    id: '6',
    title: 'Community Fridge Project',
    creator: 'The Neighborhood Spoon',
    creatorAvatar: 'https://picsum.photos/seed/creatorF/40/40',
    description: 'Install and stock public refrigerators with free, fresh food for anyone in need. Take what you need, leave what you can.',
    longDescription: 'Food insecurity affects many families in our community. The Community Fridge Project is a grassroots effort to combat hunger and reduce food waste. We place refrigerators in accessible public locations, and with the help of volunteers and local partners, keep them stocked with fresh produce, dairy, and prepared meals. Your donation helps purchase a new fridge, cover electricity costs, and buy supplemental groceries.',
    imageUrl: 'https://picsum.photos/seed/food/600/400',
    goalAmount: 5000,
    currentAmount: 1200,
    donors: 55,
    category: 'Emergency',
    endDate: '2024-12-31',
  }
];